### ISSUE TITLE
Language in RDF Data validation fails

### ISSUE THREAD

**Issue by mvidalgarcia** [labra/rdfshape#16]
When there's a white space between the object and the language label the validation fails.
I'll show you an example to be more specific:
```
<product> <label> "Blueberry Muffin" @en .
```
RDFShape says it's not valid. 
```
<product> <label> "Blueberry Muffin"@en .
```
RDFShape says it's valid.  
While in `rdfcat` both of them are valid.

**Comment by labra** [comment]
By default, the RDF Data parser is based on Jena and it seems that Jena doesn't like a space between string literals and language tags. I have also tested with my parser and it also fails. 

In RDF 1,1 Turtle grammar, [rule 128s](http://www.w3.org/TR/turtle/#grammar-production-RDFLiteral) it seems that after a string literal there can be a LANGTAG without space, so it seems that the correct behaviour is to reject it.

Maybe, rdfcat is based on a previous version of Turtle that allows whitespaces between strings and language tags.
