### ISSUE TITLE
Making RDFShape externally visible

### ISSUE THREAD

**Issue by DonRolph** [labra/rdfshape#19]
I have RDFShape working smoothly on http://localhost:9000/

How do I make it visible on my external ip address?

Thanks in advance!

**Comment by labra** [comment]
If I understand your question, in principle you should not need to do anything special. You should check which is your external IP, and rdfshape should be available at port 9000 of that IP

**Comment by DonRolph** [comment]
Yup:  it was a network issue.  My apologies.  Thanks for your response!
